services:
  - type: web
    name: laravel-docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel_postgres
          property: host
      - key: DB_PORT
        value: 5432
    databases:
      - name: laravel_postgres
        plan: free